version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ewctl
    main: ./cmd/ewctl
    binary: ewctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: ewctl
    name_template: >-
      ewctl_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - examples/config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

dockers:
  - id: ewctl
    image_templates:
      - "ghcr.io/thalysguimaraes/ewctl:{{ .Tag }}"
      - "ghcr.io/thalysguimaraes/ewctl:v{{ .Major }}"
      - "ghcr.io/thalysguimaraes/ewctl:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/thalysguimaraes/ewctl:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/thalysguimaraes/elementor-whatsapp"
      - "--platform=linux/amd64"

brews:
  - name: ewctl
    repository:
      owner: thalysguimaraes
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/thalysguimaraes/elementor-whatsapp"
    description: "Beautiful TUI for managing Elementor webhook forms with WhatsApp integration"
    license: "MIT"
    test: |
      system "#{bin}/ewctl", "version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "ewctl"

scoops:
  - name: ewctl
    repository:
      owner: thalysguimaraes
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/thalysguimaraes/elementor-whatsapp"
    description: "Beautiful TUI for managing Elementor webhook forms with WhatsApp integration"
    license: MIT

nfpms:
  - id: ewctl
    package_name: ewctl
    file_name_template: >-
      {{ .PackageName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    vendor: Thalys Guimarães
    homepage: https://github.com/thalysguimaraes/elementor-whatsapp
    maintainer: Thalys Guimarães <thalys@example.com>
    description: Beautiful TUI for managing Elementor webhook forms with WhatsApp integration
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
    recommends:
      - golang
    bindir: /usr/bin
    contents:
      - src: ./examples/config.example.yaml
        dst: /etc/ewctl/config.example.yaml
        type: config
      - src: ./README.md
        dst: /usr/share/doc/ewctl/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/ewctl/LICENSE

release:
  github:
    owner: thalysguimaraes
    name: elementor-whatsapp
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: false
  draft: false
  prerelease: auto